In [10]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0


In [11]:
print(torch.backends.mps.is_available()) # Should return True
print(torch.backends.mps.is_built())     # Should return True
device = torch.device("mps")

True
True


In [12]:
x = torch.ones(1, device=device)
print (x)

tensor([1.], device='mps:0')


### Creating Tensors

- PyTorch tensors are created using `torch.Tensor()`

In [14]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
scalar.ndim

0

In [16]:
scalar.item()

7

In [20]:
vector = torch.tensor([6,6])
vector

tensor([6, 6])

In [21]:
vector.ndim

1

In [24]:
vector.shape

torch.Size([2])

In [25]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [29]:
MATRIX.shape

torch.Size([2, 2])

In [31]:
MATRIX[1]

tensor([ 9, 10])

In [32]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])

In [36]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Random tensors

In [38]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6899, 0.7784, 0.5085, 0.7882],
        [0.7318, 0.6246, 0.6404, 0.2553],
        [0.6983, 0.5114, 0.1307, 0.6597]])

In [40]:
random_image_size_tensor = torch.rand(size=[3,224,244])
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 244]), 3)