In [10]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0


In [53]:
print(torch.backends.mps.is_available()) # Should return True
print(torch.backends.mps.is_built())     # Should return True
device = torch.device("mps")

True
True


In [12]:
x = torch.ones(1, device=device)
print (x)

tensor([1.], device='mps:0')


### Creating Tensors

- PyTorch tensors are created using `torch.Tensor()`

In [14]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
scalar.ndim

0

In [16]:
scalar.item()

7

In [20]:
vector = torch.tensor([6,6])
vector

tensor([6, 6])

In [21]:
vector.ndim

1

In [24]:
vector.shape

torch.Size([2])

In [25]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [29]:
MATRIX.shape

torch.Size([2, 2])

In [31]:
MATRIX[1]

tensor([ 9, 10])

In [32]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape

torch.Size([1, 3, 3])

In [36]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Random tensors

In [38]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6899, 0.7784, 0.5085, 0.7882],
        [0.7318, 0.6246, 0.6404, 0.2553],
        [0.6983, 0.5114, 0.1307, 0.6597]])

In [40]:
random_image_size_tensor = torch.rand(size=[3,224,244])
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 244]), 3)

In [42]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [44]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
ones.dtype

torch.float32

In [46]:
random_tensor.dtype

torch.float32

In [52]:
torch.arange(start=1,end=11,step=2)

tensor([1, 3, 5, 7, 9])

In [54]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=device, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], device='mps:0')

In [55]:
float_32_tensor.dtype

torch.float32

In [58]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='mps:0', dtype=torch.float16)

In [59]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], device='mps:0')

In [63]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long,device = device)
int_32_tensor

tensor([3, 6, 9], device='mps:0')

In [64]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], device='mps:0')

In [67]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6869, 0.6185, 0.3728, 0.1739],
        [0.1047, 0.8972, 0.5491, 0.0674],
        [0.9665, 0.7273, 0.0446, 0.2650]])

In [77]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6869, 0.6185, 0.3728, 0.1739],
        [0.1047, 0.8972, 0.5491, 0.0674],
        [0.9665, 0.7273, 0.0446, 0.2650]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [78]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [79]:
tensor - 10

tensor([-9, -8, -7])

In [80]:
tensor * 10

tensor([10, 20, 30])

In [84]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [85]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [86]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [92]:
torch.sum(tensor)

tensor(6)

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [102]:
# Shapes for matrix multiplication 
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [104]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [108]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [109]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [113]:
x.min(),torch.min(x)

(tensor(1), tensor(1))

In [115]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [123]:
torch.mean(x.type(torch.float32)),x.type(torch.float16).mean()

(tensor(46.), tensor(46., dtype=torch.float16))

In [126]:
torch.sum(x),x.sum()

(tensor(460), tensor(460))

In [127]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs 
x.argmin()

tensor(0)

In [128]:
x.argmax()

tensor(9)

In [129]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors
- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all 1 dimensions from a tensor
- Unsqueeze - add a 1 dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [130]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [131]:
x.shape

torch.Size([9])

In [132]:
x.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [141]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [142]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [151]:
torch.stack([x,x,x],dim=1)

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [160]:
x.squeeze(),x.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [163]:
x.unsqueeze(dim=0),x.unsqueeze(dim=0).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [171]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 225, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}") 
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 225, 3])
New shape: torch.Size([3, 224, 225])


In [172]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

In [173]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [174]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [178]:
x[0][2]

tensor([7, 8, 9])

In [179]:
x[0][1][2]

tensor(6)

In [185]:
x[:,0]

tensor([[1, 2, 3]])

In [186]:
x[:,:,1]

tensor([[2, 5, 8]])

In [192]:
x[0,0,:]

tensor([1, 2, 3])

In [193]:

# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [ ]:
# NumPy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor
     

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [200]:
array+1,tensor+2

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [202]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [203]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.7827, 0.8581, 0.3003, 0.1511],
        [0.8141, 0.2595, 0.0081, 0.9019],
        [0.4934, 0.6889, 0.6504, 0.2929]])
tensor([[0.2888, 0.4615, 0.0365, 0.4870],
        [0.8158, 0.2141, 0.5439, 0.0711],
        [0.2790, 0.6311, 0.8801, 0.7201]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [212]:
torch.manual_seed(42)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(42)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [215]:
torch.mps.is_available()

True

In [216]:
# Setup device agnostic code 
device = "mps" if torch.mps.is_available() else "cpu"
device

'mps'

In [217]:
torch.mps.device_count()

1

In [219]:
tensor,tensor.device

(tensor([1., 1., 1., 1., 1., 1., 1.]), device(type='cpu'))

In [222]:
tensor.to(device)

tensor([1., 1., 1., 1., 1., 1., 1.], device='mps:0')

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor.to(device).numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [224]:
tensor.cpu().numpy()

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)